### ISSUE TITLE
Allow generation of servers and base paths in `api` 

### ISSUE THREAD

**Issue by mahirk** [airtasker/spot#1050]
**Is your feature request related to a problem? Please describe.**
OpenAPI3 allows defining servers (https://swagger.io/docs/specification/api-host-and-base-path/) which can help define the scheme, description, and variables which form a server. This request is to enable spot to generate that for the OpenAPI Spec.

**Describe the solution you'd like**
Allow the definition of `server` inside the `@api` module of spot, with the following conversions:
```ts
@api({
  name: "My API",
  version: '1',
})
class Api {
  @servers
  server(
    @url
    url: 'https://{environment}.example.com/v2',
    @variables
    variables: {
      /** API description for server variables */
      environment: 'api' | 'api.dev' | 'api.staging'
    }
  ) {}
}
```

```yaml
servers:
  - url: https://{environment}.example.com/v2
    variables:
      environment:
        default: api 
        description: API description for environment variables
        enum:
          - api         
          - api.dev  
          - api.staging
```

**Describe alternatives you've considered**
Haven't thought of any other designs at this moment, likely will need to think about if it would be useful to add (a) a default value, which could be the `first` value?  and (b) multiple servers.
