### ISSUE TITLE
Add examples for request and response body

### ISSUE THREAD

**Issue by mahirk** [airtasker/spot#1075]
**Is your feature request related to a problem? Please describe.**
After https://github.com/airtasker/spot/pull/916 I was looking to add examples for the request and response body objects i.e.non parameter objects. 

**Describe the solution you'd like**
The OpenAPI spec defines the examples for this like:
```yaml
examples:
          Jessica:
            value:
              id: 10
              name: Jessica Smith
          Ron:
            value:
              id: 20
              name: Ron Stewart
```
This is different than how we define examples for parameters. In the case of a body, the example is generated for the set of properties in a given schema. 

Thinking about ways to satisfy that for a given body, there are two ways which this could be done, they both rely on the developer adding an example for every property and match the example names. I've provided only one of the ways below:
```
interface CreateUserRequest {
  /**
   * @example property-example-one
   * "Angela"
   * @example property-example-two
   * "Meena"
   */
  firstName: string;
  /**
   * @example property-example-one
   * "Kapoor"
   * @example property-example-two
   * "Shah"
   */
  lastName: string;
}
```

both of these would generate
```yaml
examples:
          property-example-one:
            value:
              firstName: Angela
              lastName: Kapoor
          property-example-one:
            value:
              firstName: Meena
              lastName: Shah
```
